### ISSUE TITLE
kismet: switch to version specific .kmax formulas

### ISSUE THREAD

**Issue by necipfazil** [paulgazz/kmax#101]
`klocalizer` switched to version specific .kmax formulas: https://github.com/paulgazz/kmax/pull/72

Do the same for `kismet`.

Possibly move this logic to `Arch` and let `klocalizer`, `kismet`, and any other tool pull the cache directory from `Arch`.

**Comment by paulgazz** [comment]
This is also related to #125

**Comment by paulgazz** [comment]
Related to #182

**Comment by paulgazz** [comment]
This has been updated: https://github.com/paulgazz/kmax/blob/236b6ec7c738e879ecf6d9b6c85858fa4444eb1a/kmax/kismet#L407
