### ISSUE TITLE
some kmax formulas are out-of-date due to having kconfig_extractor renamed to kextract

### ISSUE THREAD

**Issue by necipfazil** [paulgazz/kmax#14]
It seems like after [renaming kconfig_extractor to kextract](https://github.com/paulgazz/kmax/commit/de6af3342d7119b9e2f5b5aa464a851ae27a0c0a), some [already extracted kmax formulas](https://configtools.org/kmax/formulas/) turned out-of-date.

I used only [one of them](https://configtools.org/kmax/formulas/kmax-formulas_linux-v5.4.tar.bz2), which is for v5.4, which seem to have this problem.

Renaming the kextract files solves the issue (under `.kmax/`):
`find -name "kconfig_extract" -exec rename 's/kconfig_extract$/kextract/' '{}' \;`

____

**Reproducing:**
I was following the use cases of klocalizer from the documentation ([here](https://github.com/paulgazz/kmax/blob/master/docs/advanced.md#an-architecture-specific-compilation-unit-not-built-by-allyesconfig)).

According to the documentation, although `klocalizer` is supposed to find a valid config for `drivers/block/ps3disk.o` for `powerpc`, it finds it for `x86_64`. The output config turns out to be invalid since it can't compile `ps3disk.o`.

Running `klocalizer drivers/block/ps3disk.o` outputs:
```
INFO: Kmax formula file: .kmax/kmax
INFO: Reading kmax formulas.
INFO: Trying the following architectures: x86_64 i386 arm arm64 sparc64 sparc powerpc mips alpha arc c6x csky h8300 hexagon ia64 m68k microblaze nds32 nios2 openrisc parisc riscv s390 sh sh64 um um32 unicore32 xtensa
INFO: Using output file ".config".
INFO: Trying "x86_64"
INFO: Kclause formulas file: .kmax/kclause/x86_64/kclause
WARNING: no kextract file found: .kmax/kclause/x86_64/kextract
INFO: No kextract file available.  Assuming all configuration options are Boolean
INFO: The constraints are satisfiable.
INFO: Writing the configuration to .config
INFO: Printing model as config file to ".config".
INFO: Generated configuration for x86_64
INFO: Build with "make.cross ARCH=x86_64 olddefconfig; make.cross ARCH=x86_64 clean drivers/block/ps3disk.o".
x86_64
```

The `.config` generated by `klocalizer` includes `CONFIG_PS3_DISK=y`. However, `make.cross ARCH=x86_64 olddefconfig` 
 removes `CONFIG_PS3_DISK` from `.config`.

As a result, `make.cross ARCH=x86_64 drivers/block/ps3disk.o` fails.

In above `klocalizer` output, the following line seems suspicious:
```WARNING: no kextract file found: .kmax/kclause/x86_64/kextract```

The output for both `ls .kmax/kclause/x86_64/` and `ls .kmax/kclause/powerpc/` is:
```kclause  kconfig_extract```

I installed the kmax from repository (as in [here](https://github.com/paulgazz/kmax/blob/master/docs/advanced.md#install-from-repository)). The Linux source code and the kmax formulas are for v5.4, and downloaded using the sources provided [here](https://github.com/paulgazz/kmax/blob/master/docs/advanced.md#annotated-example).

**Comment by paulgazz** [comment]
The prebuilt formulas have been revised as well as the documentation so that user's no longer have to manually download them.  See #70
