### ISSUE TITLE
Linux-4.16 Generates Emply Kismet Files (Kmax 4.2/4.3)

### ISSUE THREAD

**Issue by tsehaiB** [paulgazz/kmax#159]
Kmax version: 4.2
Setup:
`sudo apt install -y python3 python3-pip python3-venv
python3 -m venv ~/env_kmax/
source ~/env_kmax/bin/activate
pip3 install kmax
sudo apt install -y flex bison bc libssl-dev libelf-dev
pip install --upgrade kmax'`

Script:
`cd ~/
wget https://cdn.kernel.org/pub/linux/kernel/v4.x/linux-4.16.tar.xz
tar -xvf linux-4.16.tar.xz
cd ~/linux-4.16/
kismet --linux-ksrc="${HOME}/linux-4.16/" -a=x86_64`

Command:

![image](https://user-images.githubusercontent.com/78447129/172073277-358451e5-aeca-4692-ba72-eef9aeaa5bdc.png)

Results in:

![image](https://user-images.githubusercontent.com/78447129/172073750-8d88103f-f3d1-4d03-af28-a81797fc17a4.png)

Command:

![image](https://user-images.githubusercontent.com/78447129/172073316-410fefe5-c5a4-4f57-8d69-86ca8bffeed2.png)

Results in:

![image](https://user-images.githubusercontent.com/78447129/172073742-9e8755ac-3f69-4326-a989-6fa2f09620b5.png)

These results have been replicated (on the same setup), for
https://cdn.kernel.org/pub/linux/kernel/v4.x/linux-4.14.tar.xz
https://cdn.kernel.org/pub/linux/kernel/v4.x/linux-4.9.tar.xz
https://cdn.kernel.org/pub/linux/kernel/v4.x/linux-4.2.tar.xz
https://cdn.kernel.org/pub/linux/kernel/v3.x/linux-3.18.tar.xz
https://cdn.kernel.org/pub/linux/kernel/v3.x/linux-3.12.tar.xz 
https://cdn.kernel.org/pub/linux/kernel/v3.x/linux-3.7.tar.xz
https://cdn.kernel.org/pub/linux/kernel/v3.x/linux-3.0.tar.xz

On kmax version 4.3

**Comment by necipfazil** [comment]
Seems like kextract bug.  kextract file doesn't include select constructs.
```
# Try for v5.4, for which kismet can find select constructs to analyze:
# todo: get a linux git copy, run followings inside:
git checkout -f v5.4
kextractlinux x86_64 kextract_v5.4 --module-version next-20200430
# Following outputs 10577, which is good
grep "^select" kextract_v5.4 | wc -l 

# Try for v4.16, for which kismet finds 0 select constructs:
git checkout -f v4.16
kextractlinux x86_64 kextract_v4.16 --module-version 4.12.8
# Following outputs 0, which is bad
grep "^select" kextract_v4.16 | wc -l
wc -l kextract_v4.16 # outputs 41966, so kextract file is not empty but doesn't have selects
```
