### ISSUE TITLE
kextract 4.12.8 does not output select constructs for linux kernel v4.16

### ISSUE THREAD

**Issue by necipfazil** [paulgazz/kmax#161]
Reproduce:
```
cd linux/ # change dir to a linux git copy
git checkout -f v4.16
kextractlinux x86_64 kextract_v4.16 --module-version 4.12.8
# Following outputs 0, which is bad
grep "^select" kextract_v4.16 | wc -l
wc -l kextract_v4.16 # outputs 41966, so kextract file is not empty but doesn't have selects
```

Same doesn't happen for linux v5.4 with kextract next-20200430
```
git checkout -f v5.4
kextractlinux x86_64 kextract_v5.4 --module-version next-20200430
grep "^select" kextract_v5.4 | wc -l  # outputs 10577
```

I didn't check if this is always the case for kextract 4.12.8, or specific to a set of Linux kernel versions.

Related to https://github.com/paulgazz/kmax/issues/159

**Comment by paulgazz** [comment]
I see the issue.  kextract emits “rev_dep” for use by kclause.  “select” output was deprecated for kclause, and was commented out: https://github.com/paulgazz/kmax/blob/master/kextractors/kextractor-4.12.8/kextractor.c#L2072

“select” output was uncommented for a more recent kextract, presumably for use with kismet: https://github.com/paulgazz/kmax/blob/master/kextractors/kextractor-next-20200430/kextractor.c#L1269

We need to make sure “select” is emitted for all versions of kextract (and that works the same way as the newer versions).  All others emit it except the one above and https://github.com/paulgazz/kmax/blob/master/kextractors/kextractor-3.19/kextractor.c#L2052
