### ISSUE TITLE
Linux-3.2 Doesn't Generate A Kismet File (Kmax 4.4) 

### ISSUE THREAD

**Issue by tsehaiB** [paulgazz/kmax#178]
Setup:
`sudo apt install -y python3 python3-pip python3-venv python3 -m venv ~/env_kmax/ source ~/env_kmax/bin/activate pip3 install kmax sudo apt install -y flex bison bc libssl-dev libelf-dev pip install --upgrade kmax'`

Script:
`cd ~/`
`wget https://cdn.kernel.org/pub/linux/kernel/v3.x/linux-3.2.tar.xz`
`tar -xvf linux-3.2.tar.xz`
`cd ~/linux-3.2/`
`kismet --linux-ksrc="${HOME}/linux-3.2/" -a=x86_64`

Command:
![image](https://user-images.githubusercontent.com/78447129/183083599-d8dd2c27-afc8-4c58-af3e-22dcd54c0611.png)

Results:
![image](https://user-images.githubusercontent.com/78447129/183083695-86b8a917-3337-4711-aebc-fdb7d73bbcfc.png)

Command (same commands for v3.8):
![image](https://user-images.githubusercontent.com/78447129/183084383-f55d15e4-b9ae-45ce-9fef-6149aae46aab.png)

Results:
![image](https://user-images.githubusercontent.com/78447129/183084417-9022ec01-f9c0-4b73-acd6-7e5b5bce1f6d.png)

The results have only been replicated for v3.2 and v3.8.
https://cdn.kernel.org/pub/linux/kernel/v3.x/linux-3.2.tar.xz
https://cdn.kernel.org/pub/linux/kernel/v3.x/linux-3.8.tar.xz

On Kmax Version 4.4

**Comment by paulgazz** [comment]
kmax currently only supports kconfig back to 3.19.  Need to add older kconfig versions.
