### ISSUE TITLE
Presence conditions obtained are wrong

### ISSUE THREAD

**Issue by ekuiter** [paulgazz/kmax#2]
Hi,

I'm using Kmax to determine presence conditions for single translation units (for use in the SPLC 18 challenge case).

I set up Kmax in a Ubuntu 64-bit VM following your instructions.

Using this setup, I get the following results when running Kmax with `./covering_set.py -g <file>` on the respective file.

In some cases, the correct results are returned:

```Makefile
ifeq ($(CONFIG_A),y)
obj-$(CONFIG_B) += kcmp.o
endif

# Output SHOULD be: CONFIG_A=y && CONFIG_B=y
# Output IS:        CONFIG_B=y && CONFIG_A=y && defined(CONFIG_B) && defined(CONFIG_A)
# which is fine.
```

But here are three cases which yield wrong results (at least as I interpret them):

```Makefile
ifneq ($(CONFIG_A),y)
obj-$(CONFIG_B) += kcmp.o
endif

# Output SHOULD be: !CONFIG_A=y && CONFIG_B=y
# Output IS:        || CONFIG_B=y && CONFIG_A=y && defined(CONFIG_B) && defined(CONFIG_A)
# which is not a legal formula.

# Output after applying fix (see below):
# (CONFIG_B=y && defined(CONFIG_B) && !defined(CONFIG_A)) || (CONFIG_B=y && CONFIG_A=y && defined(CONFIG_B) && defined(CONFIG_A))
# which is better, but includes more cases than it should.
```

```Makefile
ifeq ($(CONFIG_A),y)
obj-$(CONFIG_B) += kcmp.o
else
obj-$(CONFIG_B) += kcmp.o
endif

# Output SHOULD be: CONFIG_B=y
# Output IS:        CONFIG_B=y && CONFIG_A=y && defined(CONFIG_B) && defined(CONFIG_A)
# which seems to ignore the else clause.
```

```Makefile
ifneq ($(CONFIG_A),y)
obj-y += kcmp.o
endif

# Output SHOULD be: !CONFIG_A=y
# Output IS:        || CONFIG_A=y && defined(CONFIG_A)

# Output after applying fix (see below):
# (!defined(CONFIG_A)) || (CONFIG_A=y && defined(CONFIG_A))
# which also includes cases where CONFIG_A=y.
```

This also happens when analyzing the Linux kernel using `analysis/collect_buildsystem.py`:

```
unit_pc kernel/up.o  || CONFIG_SMP=y && defined(CONFIG_SMP)
unit_pc fs/no-block.o  || defined(CONFIG_BLOCK) && CONFIG_BLOCK=y
# ...
```

First of all, there seems to be a bug in the code that translates BDDs into strings (`bdd_to_str` in `covering_set.py:718`):

```python
for sublist in self.bdd_to_cnf(condition):
    term = "" # term = "("
    factor_delim = ""
    for factor in sublist:
        term += factor_delim + factor
        factor_delim = " && "
    if len(term) > 0: # if len(term) > 1:
        expression = term_delim + term # expression += term_delim + term + ")"
        term_delim = " || "
```

This code, as is, only returns the last clause of the formula, not the whole formula (resulting in the `|| ...` outputs above). The fix is straightforward (the `expression` has to be appended to: `+=`).

Still, some presence conditions are wrong (shown above as `output after applying fix ...`).

Do you have any idea what could cause this - is my setup wrong, or does Kmax simply not support these cases well? Can you reproduce the issue?

Something else I noticed: Supposedly, the BDD is represented as a formula in CNF, which to my understanding is structured as

```
List of Clauses (which are combined using &&) of
    Lists of Literals (which are combined using ||)
```

However, the `bdd_to_str` function seems to concatenate presence conditions the opposite way, like a DNF formula:
```
List of Terms -> combined with ||, inside are
    Lists of Factors -> combined with &&
```
where I believe *Factor = Literal* and *Term = Clause*. Am I missing something?

Both ways of concatenating a presence condition lead to wrong results, though - maybe you can help me out.

**Comment by paulgazz** [comment]
These tests now produce expected results, at least when treating
configuration options as Boolean.  These four test cases are now the
repo as `tests/ekuiter{1-4}`.  4ece5835ada5b13420caa5ce81a50fd5b36d1d45


### `ekuiter1`

    ifeq ($(CONFIG_A),y)
    obj-$(CONFIG_B) += kcmp.o
    endif

    # Output SHOULD be: CONFIG_A=y && CONFIG_B=y
    # Output IS:        CONFIG_B=y && CONFIG_A=y && defined(CONFIG_B) && defined(CONFIG_A)
    # which is fine.

Output is now

    unit_pc tests/kcmp.o (CONFIG_B && CONFIG_A)

### `ekuiter2`

    ifneq ($(CONFIG_A),y)
    obj-$(CONFIG_B) += kcmp.o
    endif

    # Output SHOULD be: !CONFIG_A=y && CONFIG_B=y
    # Output IS:        || CONFIG_B=y && CONFIG_A=y && defined(CONFIG_B) && defined(CONFIG_A)
    # which is not a legal formula.

    # Output after applying fix (see below):
    # (CONFIG_B=y && defined(CONFIG_B) && !defined(CONFIG_A)) || (CONFIG_B=y && CONFIG_A=y && defined(CONFIG_B) && defined(CONFIG_A))
    # which is better, but includes more cases than it should.

Output is now

    unit_pc tests/kcmp.o (CONFIG_B && (! CONFIG_A))

### `ekuiter3`

    ifeq ($(CONFIG_A),y)
    obj-$(CONFIG_B) += kcmp.o
    else
    obj-$(CONFIG_B) += kcmp.o
    endif

     # Output SHOULD be: CONFIG_B=y
     # Output IS:        CONFIG_B=y && CONFIG_A=y && defined(CONFIG_B) && defined(CONFIG_A)
     # which seems to ignore the else clause.

Output is now

    unit_pc tests/kcmp.o ((CONFIG_B && (! CONFIG_A)) || (CONFIG_B && CONFIG_A))
    
although it could use some simplification.

### `ekuiter4`

    ifneq ($(CONFIG_A),y)
    obj-y += kcmp.o
    endif

    # Output SHOULD be: !CONFIG_A=y
    # Output IS:        || CONFIG_A=y && defined(CONFIG_A)

    # Output after applying fix (see below):
    # (!defined(CONFIG_A)) || (CONFIG_A=y && defined(CONFIG_A))
    # which also includes cases where CONFIG_A=y.
    
Output is now

    unit_pc tests/kcmp.o (! CONFIG_A)
