### ISSUE TITLE
Report random seed used by z3 to assist in bug replicability

### ISSUE THREAD

**Issue by paulgazz** [paulgazz/kmax#51]
Currently, when generating an arbitrary configuration, z3 may use some randomness.  See if it's possible to report this in the output to help with bug reporting and bug replication in the future.

**Comment by Uclydde** [comment]
Z3 uses a seed of `0`, unless specifically set by the user.

**Comment by paulgazz** [comment]
Good to know.  Is there anyway to know the current state of the RNG if used for new models or whether it’s reset?
