### ISSUE TITLE
Formula in DIMACS format

### ISSUE THREAD

**Issue by acherm** [paulgazz/kmax#54]
Hi, 

would it be possible to export the extracted formula in DIMACS format (for further analysis with SAT solvers)? 
Right now it seems the SMTLIB format is internally used with Z3. Am I right? 

My use case is to obtain the SAT formula for a given architecture (eg x86_64). 
Then the hope is to generate random, valid .config files out of SAT solutions of the formula.
(seems related to https://github.com/paulgazz/kmax/issues/12) 

Thanks for this great work! 

Mathieu

**Comment by paulgazz** [comment]
This is now supported with the `--save-dimacs FILENAME` option.

Note that klocalizer can already sample configuration by getting models from z3 then converting to the .config file format.  But this option can be useful for SAT-based samplers.

**Comment by acherm** [comment]
Hi Paul, 

thanks a lot!

I wax expecting `--save-dimacs` to be part of `kextract`...
Does `--save-dimacs` over `klocalizer` serialize a "global" SAT formula? Or is it a specific SAT formula for a compilation unit? 
In fact I was disturbed by having to specify the compilation_unit `klocalizer --save-dimacs compilation_unit.o` and I was thinking 
`klocalizer --save-dimacs` could be enough. 
But maybe I don't get something and the DIMACS formula is "just" a serialization of a specific .config and not a logical representation of the whole configuration space (I'm interested by the latter) 

Btw, I have difficulties to use `kextract` over linux 5.4 and 5.8: 
`kextract --extract -e ARCH=x86_64 -e SRCARCH=x86 -e KERNELVERSION=kcu -e srctree=./ -e CC=cc -e LD=ld Kconfig > kextract` 

here is the trace: 
```
:/linux-5.8# kextract --extract -e ARCH=x86_64 -e SRCARCH=x86 -e KERNELVERSION=kcu -e srctree=./ -e CC=cc -e LD=ld Kconfig > kextract
init/Kconfig:6: syntax error
init/Kconfig:5: unknown statement "option"
init/Kconfig:6: invalid statement
init/Kconfig:7: invalid statement
init/Kconfig:8: invalid statement
init/Kconfig:9: invalid statement
init/Kconfig:1724: syntax error
init/Kconfig:1723: unknown statement "option"
init/Kconfig:1724: invalid statement
init/Kconfig:1725: invalid statement
init/Kconfig:1726: unknown statement "This"
init/Kconfig:1727: unknown statement "an"
init/Kconfig:1728:warning: ignoring unsupported character '.'
init/Kconfig:1728: unknown statement "for"
init/Kconfig:2012: syntax error
init/Kconfig:2011: unknown statement "option"
init/Kconfig:2012: invalid statement
init/Kconfig:2013: unknown statement "Kernel"
init/Kconfig:2014:warning: ignoring unsupported character ','
init/Kconfig:2014: unknown statement "be"
init/Kconfig:2015:warning: ignoring unsupported character '.'
init/Kconfig:2015: unknown statement "permanently"
init/Kconfig:2016:warning: ignoring unsupported character '.'
init/Kconfig:2016:warning: ignoring unsupported character ','
init/Kconfig:2016: unknown statement "tool"
init/Kconfig:2017: unknown statement "many"
init/Kconfig:2018:warning: ignoring unsupported character ':'
init/Kconfig:2018: unknown statement "answering"
init/Kconfig:2019: unknown statement "useful"
init/Kconfig:2020:warning: ignoring unsupported character '.'
init/Kconfig:2020:warning: ignoring unsupported character ','
init/Kconfig:2020: unknown statement "for"
init/Kconfig:2021:warning: ignoring unsupported character ','
init/Kconfig:2021:warning: ignoring unsupported character ','
init/Kconfig:2021:warning: ignoring unsupported character ','
init/Kconfig:2021:warning: ignoring unsupported character '.'
init/Kconfig:2021: unknown statement "modprobe"
init/Kconfig:2023:warning: ignoring unsupported character ','
init/Kconfig:2023:warning: multi-line strings not supported
init/Kconfig:2023: unknown statement "If"
init/Kconfig:2024:warning: multi-line strings not supported
init/Kconfig:2024: unknown statement "modules_install"
init/Kconfig:2025: unknown statement "where"
init/Kconfig:2026:warning: ignoring unsupported character '.'
init/Kconfig:2026: unknown statement "this"
init/Kconfig:2028:warning: ignoring unsupported character ','
init/Kconfig:2028:warning: ignoring unsupported character '.'
init/Kconfig:2028: unknown statement "If"
```

**Comment by paulgazz** [comment]
Hi @acherm,

Thanks for trying out the tool!  `--save-dimacs` takes a parameter for the name of a file to save the DIMACS output to, e.g., the following will get the whole Kconfig spec for x86_64,

    klocalizer --save-dimacs x86_64.dimacs

`klocalizer` can run both with and without taking any compilation unit, which is why this will work, in which case it just uses the formula for the whole Kconfig specification.  Sorry for the confusion on this!  `klocalizer` wraps `kextract` and `kclause` (and other tools) with extra functionality, which is why I added the option there.

As for `kextract`, the issue here is that the Kconfig syntax gradually changes over time, and the latest one is not compatible with 5.4.  Our solution is to just have parsers from several versions of the kernel.  `klocalizer` will try to pick the right one based on the kernel source version.  And after running it, the kextract file will be cached in `.kmax/5.4.0/x86_64/kextract`, depending on what version and arch were run.  If you’d like to manually pick Kconfig parser, you can use the `—module-version` flag to `kextract`, e.g.,

    kextract  --module-version next-20200430 --extract -e ARCH=x86_64 -e SRCARCH=x86 -e KERNELVERSION=kcu -e srctree=./ -e CC=cc -e LD=ld Kconfig > kextract

Try these commands out and please let me know if you still have issues getting them to work.

**Comment by acherm** [comment]
Thanks @paulgazz for the answer. 
I now better understand the use of `klocalizer`. 

The translation into DIMACS is realized through Z3 facilities:
https://github.com/paulgazz/kmax/blob/master/kmax/klocalizer#L522-L528 

I have a few remarks (experiments on version 5.4):
 * several DIMACS variables are called `and` and `or`. Is it normal?
 * how modules' value (`m` in .config) can be set to options? It seems to be either yes or no...
 * the option CONFIG_MODULES is not there... is it on purpose?

Other question: klocalizer is relying on kextract... does `klocalizer` use the "picking the right parser" strategy by default? Because klocalizer works out of the box, not extract that requires the "module-version" trick. 

In parallel to using DIMACS and a SAT solver, I'm also considering using Z3 directly. 
Your command with `kextract` works nicely ie I obtain a file called kextract without apparent error messages ;)
Thanks!

I then tried to apply `kclause --remove-orphaned-nonvisible < kextract > kclause` and do succeed. 
This kclause file has, however, a strange encoding (see below an excerpt). 

```
head kclause 
(dp0
VCONFIG_UNWINDER_ORC
p1
(lp2
V; benchmark generated from python API\u000a(set-info :status unknown)\u000a(declare-fun CONFIG_UNWINDER_FRAME_POINTER () Bool)\u000a(declare-fun CONFIG_UNWINDER_ORC () Bool)\u000a(assert\u000a (let (($x25 (not CONFIG_UNWINDER_FRAME_POINTER)))\u000a (let (($x23 (not CONFIG_UNWINDER_ORC)))\u000a (or $x23 $x25))))\u000a(check-sat)\u000a
p3
aV; benchmark generated from python API\u000a(set-info :status unknown)\u000a(declare-fun CONFIG_UNWINDER_GUESS () Bool)\u000a(declare-fun CONFIG_UNWINDER_ORC () Bool)\u000a(assert\u000a (let (($x28 (not CONFIG_UNWINDER_GUESS)))\u000a (let (($x23 (not CONFIG_UNWINDER_ORC)))\u000a (or $x23 $x28))))\u000a(check-sat)\u000a
p4
aV; benchmark generated from python API\u000a(set-info :status unknown)\u000a(declare-fun CONFIG_UNWINDER_ORC () Bool)\u000a(declare-fun CONFIG_X86_64 () Bool)\u000a(assert\u000a (or (and CONFIG_X86_64 (or (not CONFIG_UNWINDER_ORC) CONFIG_X86_64)) (and (not CONFIG_X86_64) (not CONFIG_UNWINDER_ORC))))\u000a(check-sat)\u000a
p5
``` 
I've tried to read it in Z3, but cannot...

```
>>> from z3 import *
>>> s = Solver()
>>> s.from_file('kclause')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mathieuacher/SANDBOX/kmax/z3/venv/lib/python3.7/site-packages/z3/z3.py", line 7111, in from_file
    Z3_solver_from_file(self.ctx.ref(), self.solver, filename)
  File "/home/mathieuacher/SANDBOX/kmax/z3/venv/lib/python3.7/site-packages/z3/z3core.py", line 3858, in Z3_solver_from_file
    _elems.Check(a0)
  File "/home/mathieuacher/SANDBOX/kmax/z3/venv/lib/python3.7/site-packages/z3/z3core.py", line 1443, in Check
    raise self.Exception(self.get_error_message(ctx, err))
z3.z3types.Z3Exception: b'(error "line 72775 column 3: invalid s-expression, unexpected end of file")\n'
```

Any help and explanations are welcome :)
Thanks a lot!

**Comment by paulgazz** [comment]
> Thanks @paulgazz for the answer. I now better understand the use of `klocalizer`.
> 
> The translation into DIMACS is realized through Z3 facilities: https://github.com/paulgazz/kmax/blob/master/kmax/klocalizer#L522-L528
> 
> I have a few remarks (experiments on version 5.4):
> 
>     * several DIMACS variables are called `and` and `or`. Is it normal?
> 
>     * how modules' value (`m` in .config) can be set to options? It seems to be either yes or no...
> 
>     * the option CONFIG_MODULES is not there... is it on purpose?
> 

Hi @acherm,

I think z3 uses Tseitin transform to get the DIMACS format, which might be where the extra variables come from.  As for modules, we don't model them yet, instead collapsing 'y' and 'm' both to true.  Eventually we'd like to model true tristate values in z3 directly, though that would complicate the DIMACS format.  The DIMACS output omits free variables that have no constraints on them, which is why CONFIG_MODULES doesn't show up there, since it's unconstrained.

> 
> Other question: klocalizer is relying on kextract... does `klocalizer` use the "picking the right parser" strategy by default? Because klocalizer works out of the box, but not kextract that requires the "module-version" trick.

Yes, `klocalizer` does the job of figuring out the source version and telling `kextract` which one to use.

> I then tried to apply `kclause --remove-orphaned-nonvisible < kextract > kclause` and do succeed. This kclause file has, however, a strange encoding (see below an excerpt).
> 
> I've tried to read it in Z3, but cannot...
> 
> 
> Any help and explanations are welcome :) Thanks a lot!

Apologies for the confusion on this.  `kclause` emits a pickled python data structure that maps configuration option names to z3-formatted formulas.  `klocalizer` unpickles and combines all constraints internally.  I'll add a feature request for kclause to be able to emit the constraints as pure z3, but for now, please use the following code to read in the kclause output file and combine the constraints into a z3 solver (and emit as a single z3-formatted string if desired):

```
import z3
import pickle

# this program will read the kclause file format, combine all
# constraints for each configuration option, and output a single
# combined z3 formula for all
path_to_kclause_file = ".kmax/5.4.0/kclause/x86_64/kclause"
with open(path_to_kclause_file, "rb") as f:
  # unpickle kclause output
  kclause_formulas = pickle.load(f)

  # parse z3 formulas for each configuration option
  kclause_constraints = {}
  for var in kclause_formulas:
    kclause_constraints[var] = [ z3.parse_smt2_string(clause) for clause in kclause_formulas[var] ]

  # collect constraints from all configuration options
  constraints = []
  for var in kclause_constraints:
    for z3_clause in kclause_constraints[var]:
      constraints.extend(z3_clause)
  s = z3.Solver()
  s.add(constraints)
  smt2_str = s.to_smt2()
  print(smt2_str)
```
